# Generated by Django 4.2 on 2024-01-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='custom_url_key',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='shorted_url/qr/'),
        ),
    ]
