# Generated by Django 4.2 on 2024-01-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0002_shortenedurl_custom_url_key_shortenedurl_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
